### ISSUE TITLE
Tronbox deploy contract doesn't support array function args ?

### ISSUE THREAD

**Issue by HackFisher** [evolutionlandorg/tron-contracts#10]
code in tronbox migration scripts
```
    await deployer.deploy(MintAndBurnAuthority, [[GringottsBank.address, dividendPool.address]]);
    await kton.setAuthority(MintAndBurnAuthority.address);
```

```
  Deploying MintAndBurnAuthority...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: invalid address (arg="", coderType="address", value=["41e4fe008fd0bd625438be8753bf20db722d4d6c7a","41b2755f842a8cdee8ea5d6f0135f6acf811febf74"], version=4.0.7)
    at /usr/local/lib/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:158:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by HackFisher** [comment]
https://github.com/trufflesuite/truffle/issues/1013

https://github.com/ethereum/web3.js/issues/1241

**Comment by HackFisher** [comment]
https://github.com/evolutionlandorg/tron-contracts/pull/21/commits/bc6b98167a268e7400c37ca78b2b3d9f6d00c350

**Comment by HackFisher** [comment]
Current tronbox and tronweb didn't do well on the adaptor: constructor address arrays (it is still using the format or ethereum address)
