### ISSUE TITLE
TRON seems to have issues with library deployment.

### ISSUE THREAD

**Issue by HackFisher** [evolutionlandorg/tron-contracts#4]
```
  Deploying LocationCoder...
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:156:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by ghost** [comment]
but I still have this problem and cannot detect where compiler failed

**Comment by ghost** [comment]
the solution was remove second library (not best practice)

**Comment by CryptoZ258** [comment]
How to solve this problem? tronbox seems a lot of bugs

**Comment by ganiular** [comment]
Hello I am having same problem. I never know how to get out of the error.

`
    Deploying GamaBish...
ERROR: TypeError: Cannot read property 'forEach' of undefined
`

**Comment by ganiular** [comment]
I have detect the problem to mine project. It could work for you as well.

The solution is to include a function that takes primitive parameter and return primitive value to the contract or library that is having such issue.

For example:

`
function doNothing(uint para) public pure returns(uint value){}
`

**Comment by 420visions** [comment]
> I have detect the problem to mine project. It could work for you as well.
> 
> The solution is to include a function that takes primitive parameter and return primitive value to the contract or library that is having such issue.
> 
> For example:
> 
> `function doNothing(uint para) public pure returns(uint value){}`

What kind of magic is this? This worked for me.

**Comment by patrick0xand** [comment]
Why don't I find this magic sooner?! Worked like a charm
