### ISSUE TITLE
Error: invalid bytes32 value (arg="", coderType="bytes32", value="GOLD", version=4.0.7

### ISSUE THREAD

**Issue by HackFisher** [evolutionlandorg/tron-contracts#5]
```
Error encountered, bailing. Network state unknown. Review successful transactions manually.
Error: Error: invalid bytes32 value (arg="", coderType="bytes32", value="GOLD", version=4.0.7)
    at /usr/local/lib/node_modules/tronbox/build/webpack:/packages/tronwrap/index.js:156:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
await deployer.deploy(StandardERC223, "GOLD");
```

**Comment by HackFisher** [comment]
https://github.com/ethereum/remix-ide/issues/1301

**Comment by HackFisher** [comment]
Work around by changing contract key to string.
